table 'US Balance Sheet FY 2025'
	isHidden
	lineageTag: f5a483e4-4747-4e3d-ade0-f49857fdc946

	column 'GL Code'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c81acd3a-c804-432d-8580-6ad5c6691433
		summarizeBy: count
		sourceColumn: GL Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GL Account'
		dataType: string
		isHidden
		lineageTag: fceee538-69df-4adc-aadc-ee885ed3b72f
		summarizeBy: none
		sourceColumn: GL Account

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8c9889b6-021f-4e5b-b468-aadd3f9e3ed9
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: decimal
		isHidden
		formatString: "Rs"#,0.###############;-"Rs"#,0.###############;"Rs"#,0.###############
		lineageTag: 56b2710b-0d18-4a28-9856-9aa1884ee710
		summarizeBy: sum
		sourceColumn: Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-PK"}

	column Type
		dataType: string
		isHidden
		lineageTag: 6a5b1400-a7f4-4b2c-8474-c9f11b210758
		summarizeBy: none
		sourceColumn: Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		isHidden
		lineageTag: 1dbb05aa-bddc-4456-97ef-20af1ffa6e1e
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		isHidden
		lineageTag: b04e56cd-1219-4b52-adf1-deab9913de64
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'US Balance Sheet FY 2025' = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Data 1 Financial\CSV\OMNITRONICS,+INC._Balance+Sheet - FY 2025.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}}),
				    #"Demoted Headers" = Table.DemoteHeaders(#"Changed Type"),
				    #"Removed Top Rows" = Table.Skip(#"Demoted Headers",5),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"", type text}, {"Jul 2024", type text}, {"Aug 2024", type text}, {"Sep 2024", type text}, {"Oct 2024", type text}, {"Nov 2024", type text}, {"Dec 2024", type text}, {"Jan 2025", type text}, {"Feb 2025", type text}, {"Mar 2025", type text}, {"Apr 2025", type text}, {"May 2025", type text}, {"Jun 2025", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"", Text.Trim, type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Trimmed Text", "", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {".1", ".2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{".1", Int64.Type}, {".2", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type2", {{".1", null}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Errors",{{".1", "GL Code"}, {".2", "GL Account"}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"GL Account", "GL Code"}, "Attribute", "Value"),
				    #"Sorted Rows" = Table.Sort(#"Unpivoted Other Columns",{{"Value", Order.Descending}}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Sorted Rows", "Attribute", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Attribute.1", "Attribute.2"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Attribute.1", type text}, {"Attribute.2", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type3",{"Attribute.2"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Attribute.1", "Month"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Country", each "2025"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"GL Code", "GL Account", "Month", "Country", "Value"}),
				    #"Added Custom1" = Table.AddColumn(#"Reordered Columns", "Country.1", each "USA"),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Type", each "BALANCE SHEET"),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom2",{"GL Code", "GL Account", "Type", "Month", "Country", "Value", "Country.1"}),
				    #"Added Custom3" = Table.AddColumn(#"Reordered Columns1", "Month 2", each if [Month] = "Jan" then "January" else 
				if [Month] = "Feb" then "February" else 
				if [Month] = "Mar" then "March" else
				if [Month] = "Apr" then "April" else
				if [Month] = "Jun" then "June" else
				if [Month] = "Jul" then "July" else
				if [Month] = "Aug" then "August" else
				if [Month] = "Sep" then "September" else
				if [Month] = "Oct" then "October" else
				if [Month] = "Nov" then "November" else
				if [Month] = "Dec" then "December" else
				
				[Month]),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom3",{"GL Code", "GL Account", "Type", "Month", "Month 2", "Country", "Value", "Country.1"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns2",{"Month"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"Month 2", "Month"}, {"Country", "Year"}, {"Country.1", "Country"}, {"Value", "Amount"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Year", Int64.Type}, {"Amount", Currency.Type}})
				in
				    #"Changed Type4"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

