table 'US P&L FY 2026'
	isHidden
	lineageTag: 71fa4db2-a9c5-4676-b1cb-facec82188c4

	column 'GL Code'
		dataType: string
		isHidden
		lineageTag: 59273e55-db33-4f63-84f0-e0c395211494
		summarizeBy: none
		sourceColumn: GL Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'GL Account'
		dataType: string
		isHidden
		lineageTag: f85d4edf-b46f-4bc2-8779-cd478c7ec318
		summarizeBy: none
		sourceColumn: GL Account

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		isHidden
		lineageTag: 64e429dc-496d-415f-80f0-0b1c0b101e24
		summarizeBy: none
		sourceColumn: Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		isHidden
		lineageTag: aae55917-b98f-4287-8751-4d259d1c9459
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: double
		isHidden
		formatString: 0
		lineageTag: ae79120e-0279-49fa-92f7-96586fbc56a4
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: decimal
		isHidden
		formatString: "Rs"#,0.###############;-"Rs"#,0.###############;"Rs"#,0.###############
		lineageTag: 475aedef-c15a-4d5c-9538-a0d034c47a15
		summarizeBy: sum
		sourceColumn: Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-PK"}

	column Country
		dataType: string
		isHidden
		lineageTag: d84f9c5e-78b5-43dd-b117-6101df36b7c7
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'US P&L FY 2026' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Data 1 Financial\CSV\OMNITRONICS,+INC._Profit+and+Loss - FY 2026.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",4),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"", type text}, {"Jul 2025", type text}, {"Aug 2025", type text}}),
				    #"Removed Top Rows1" = Table.Skip(#"Changed Type1",1),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Top Rows1", {""}, "Attribute", "Value"),
				    #"Trimmed Text" = Table.TransformColumns(#"Unpivoted Other Columns",{{"", Text.Trim, type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Trimmed Text", "", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {".1", ".2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{".1", type text}, {".2", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{".1", "GL Code"}, {".2", "GL Account"}, {"Attribute", "Month"}, {"Value", "Amount"}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Renamed Columns",{{"Month", Text.Trim, type text}}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Trimmed Text1", "Month", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Month.1", "Month.2"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Month.1", type text}, {"Month.2", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type3",{{"Month.2", "Year"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",2025,2026,Replacer.ReplaceValue,{"Year"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value",{"GL Code", "GL Account", "Month.1", "Amount", "Year"}),
				    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "Country", each "USA"),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom",{"GL Code", "GL Account", "Month.1", "Amount", "Country", "Year"}),
				    #"Added Custom1" = Table.AddColumn(#"Reordered Columns1", "Type", each "PROFIT & LOSS"),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom1",{"GL Code", "GL Account", "Type", "Month.1", "Year", "Amount", "Country"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns2",{{"Month.1", "Month"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns2","Jul","July",Replacer.ReplaceText,{"Month"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Aug","August",Replacer.ReplaceText,{"Month"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value2",{{"Amount", Currency.Type}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type4", {{"Amount", null}}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Errors", each ([Month] = "July") and ([GL Account] = "Hardware Sales"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

